version: '3.3'

services:
  psql:
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=vmiguel
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - './postgreSQL_db:/var/lib/postgresql/data'