version: '3.3'

services:
  psql:
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=vmiguel
      - POSTGRES_USER=vmiguel
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - './postgreSQL_db:/var/lib/postgresql/data'



  pgad:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80



  mysql:
    image: 'mysql:5'
    environment:
      - MYSQL_DATABASE=vmiguel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - './mySQL_db:/var/lib/mysql'



  pma:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_HOST=mysql
    ports:
      - 8080:80